export default {
	items: [
		{
			id: "navigation",
			title: "Navigation",
			type: "group",
			icon: "icon-navigation",
			children: [
				{
					id: "dashboard",
					title: `User's Dashboard`,
					type: "item",
					url: "/dashboard/default",
					icon: "feather icon-home",
				},
			],
		},
		{
			id: "ui-element",
			title: "UI ELEMENT",
			type: "group",
			icon: "icon-ui",
			children: [
				{
					id: "basic",
					title: "Component",
					type: "collapse",
					icon: "feather icon-box",
					children: [
						{
							id: "button",
							title: "Button",
							type: "item",
							url: "/basic/button",
						},
						{
							id: "badges",
							title: "Badges",
							type: "item",
							url: "/basic/badges",
						},
						{
							id: "breadcrumb-pagination",
							title: "Breadcrumb & Pagination",
							type: "item",
							url: "/basic/breadcrumb-paging",
						},
						{
							id: "collapse",
							title: "Collapse",
							type: "item",
							url: "/basic/collapse",
						},
						{
							id: "tabs-pills",
							title: "Tabs & Pills",
							type: "item",
							url: "/basic/tabs-pills",
						},
						{
							id: "typography",
							title: "Typography",
							type: "item",
							url: "/basic/typography",
						},
					],
				},
			],
		},
		{
			id: "ui-forms",
			title: "Forms",
			type: "group",
			icon: "icon-group",
			children: [
				{
					id: "form-basic",
					title: "Forms Elements",
					type: "item",
					url: "/forms/form-basic",
					icon: "feather icon-file-text",
				},
				{
					id: "form-basic",
					title: "Message Form",
					type: "item",
					url: "/forms/message-form",
					icon: "feather icon-file-text",
				},
				{
					id: "form-basic",
					title: "Loan Application",
					type: "item",
					url: "/forms/form-basic",
					icon: "feather icon-file-text",
				},
				{
					id: "form-basic",
					title: "Hire Purchase Application",
					type: "item",
					url: "/forms/form-basic",
					icon: "feather icon-file-text",
				},
				{
					id: "bootstrap",
					title: "Table",
					type: "item",
					icon: "feather icon-server",
					url: "/tables/bootstrap",
				},
			],
		},
		{
			id: "chart-maps",
			title: "Chart & Maps",
			type: "group",
			icon: "icon-charts",
			children: [
				{
					id: "charts",
					title: "Charts",
					type: "item",
					icon: "feather icon-pie-chart",
					url: "/charts/nvd3",
				},
				{
					id: "maps",
					title: "Map",
					type: "item",
					icon: "feather icon-map",
					url: "/maps/google-map",
				},
			],
		},
		{
			id: "member-welfare",
			title: "Member Welfare Support",
			type: "group",
			icon: "icon-charts",
			children: [
				{
					id: "insurance",
					title: "X-Life Cover Programme",
					type: "item",
					icon: "feather icon-pie-chart",
					url: "/charts/nvd3",
				},
				{
					id: "pension",
					title: "Micro Pension Scheme for Farmer",
					type: "item",
					icon: "feather icon-map",
					url: "/maps/google-map",
				},
			],
		},
		{
			id: "capacity-building",
			title: "Training and Capacity Building",
			type: "group",
			icon: "icon-charts",
			children: [
				{
					id: "training-calendar",
					title: "Empower Training Calendar",
					type: "item",
					icon: "feather icon-pie-chart",
					url: "/charts/nvd3",
				},
				{
					id: "literacy-programme",
					title: "Farmer Literacy Programme Calendar",
					type: "item",
					icon: "feather icon-map",
					url: "/maps/google-map",
				},
				{
					id: "e-learning",
					title: "E-Learning Centre",
					type: "item",
					icon: "feather icon-pie-chart",
					url: "/charts/nvd3",
				},
				{
					id: "event-schedule",
					title: "Special Event Schedule",
					type: "item",
					icon: "feather icon-pie-chart",
					url: "/charts/nvd3",
				},
			],
		},
		{
			id: "pages",
			title: "Pages",
			type: "group",
			icon: "icon-pages",
			children: [
				{
					id: "auth",
					title: "Authentication",
					type: "collapse",
					icon: "feather icon-lock",
					badge: {
						title: "New",
						type: "label-danger",
					},
					children: [
						{
							id: "signup-1",
							title: "Sign up",
							type: "item",
							url: "/auth/signup-1",
							target: true,
							breadcrumbs: false,
						},
						{
							id: "signin-1",
							title: "Sign in",
							type: "item",
							url: "/auth/signin-1",
							target: true,
							breadcrumbs: false,
						},
					],
				},

				{
					id: "sample-page",
					title: "Sample Page",
					type: "item",
					url: "/sample-page",
					classes: "nav-item",
					icon: "feather icon-sidebar",
				},
				{
					id: "docs",
					title: "Documentation",
					type: "item",
					url: "/docs",
					classes: "nav-item",
					icon: "feather icon-help-circle",
				},
				{
					id: "docs",
					title: "Membership Category",
					type: "item",
					url: "/docs",
					classes: "nav-item",
					icon: "feather icon-help-circle",
				},
				{
					id: "docs",
					title: "Agricbusiness Connect",
					type: "item",
					url: "/docs",
					classes: "nav-item",
					icon: "feather icon-help-circle",
				},
				{
					id: "menu-level",
					title: "Menu Levels",
					type: "collapse",
					icon: "feather icon-menu",
					children: [
						{
							id: "menu-level-1.1",
							title: "Menu Level 1.1",
							type: "item",
							url: "#!",
						},
						{
							id: "menu-level-1.2",
							title: "Menu Level 2.2",
							type: "collapse",
							children: [
								{
									id: "menu-level-2.1",
									title: "Menu Level 2.1",
									type: "item",
									url: "#",
								},
								{
									id: "menu-level-2.2",
									title: "Menu Level 2.2",
									type: "collapse",
									children: [
										{
											id: "menu-level-3.1",
											title: "Menu Level 3.1",
											type: "item",
											url: "#",
										},
										{
											id: "menu-level-3.2",
											title: "Menu Level 3.2",
											type: "item",
											url: "#",
										},
									],
								},
							],
						},
					],
				},
				{
					id: "membership-categories",
					title: "Membership Categories",
					type: "item",
					url: "#",
					classes: "nav-item",
					icon: "feather icon-power",
				},
				{
					id: "profile",
					title: "Profile & Settings",
					type: "item",
					url: "#",
					classes: "nav-item",
					icon: "feather icon-power",
				},
				{
					id: "disabled-menu",
					title: "Contact Admin",
					type: "item",
					url: "#",
					classes: "nav-item",
					icon: "feather icon-power",
                },
                {
					id: "disabled-menu",
					title: "Disabled Menu",
					type: "item",
					url: "#",
					classes: "nav-item disabled",
					icon: "feather icon-power",
				},
				/*{
                    id: 'buy-now',
                    title: 'Buy Now',
                    type: 'item',
                    icon: 'feather icon-user',
                    classes: 'nav-item',
                    url: 'https://codedthemes.com',
                    target: true,
                    external: true,
                    badge: {
                        title: 'v1.0',
                        type: 'label-primary'
                    }
                }*/
			],
		},
	],
};
